import json
import re
import shutil
import zipfile
from pathlib import Path

from core.compatibility import (
    DEFAULT_PROFILE_KEY,
    MinecraftProfile,
    get_profile,
)
from core.models import RestrictionRow

NAMESPACE = "jobsgenerator"
SUPPORTED_RESTRICTION_TYPES = {
    "craft",
    "smelt",
    "brew",
    "enchant",
    "repair",
    "use_item",
    "break_block",
    "item_break_block",
    "place_block",
    "hurt_entity",
}
USE_RESTRICTION_TYPES = {
    "use_item",
    "break_block",
    "item_break_block",
    "place_block",
    "hurt_entity",
}
JOB_ALIASES = {
    # Starsze wersje generatora błędnie używały nieistniejącego
    # domyślnie ID "warrior". W Jobs+ rolę bojową pełni Hunter.
    "warrior": "hunter",
}


def safe_name(item_id: str) -> str:
    return re.sub(r"[^a-z0-9_.-]+", "_", item_id.lower().replace(":", "__"))


def restriction_json(item_id: str, job: str, level: int, types: list[str]) -> dict:
    job = JOB_ALIASES.get(job, job)
    return {
        "icon": {"id": item_id},
        "types": types,
        "conditions": [
            {
                "type": "jobsplus:job_level",
                "job": f"jobsplus:{job}",
                "level": level,
                "inverted": True,
            },
            {
                "type": "arc:item",
                "item": {"id": item_id},
                # Arc domyślnie porównuje także uszkodzenia, zaklęcia i inne
                # komponenty. Restrykcja ma obejmować każdą kopię danego itemu.
                "check_components": False,
            },
        ],
    }


def generate_pack(
    rows: list[RestrictionRow],
    destination_zip: Path,
    language: str = "pl",
    profile: MinecraftProfile | str = DEFAULT_PROFILE_KEY,
) -> tuple[int, list[str]]:
    if isinstance(profile, str):
        profile = get_profile(profile)
    build_dir = destination_zip.parent / ".jobsgenerator_build"
    if build_dir.exists():
        shutil.rmtree(build_dir)
    restrictions_dir = build_dir / "data" / NAMESPACE / "itemrestrictions" / "restrictions"
    restrictions_dir.mkdir(parents=True)
    metadata = profile.pack_metadata(
        "Jobs+ restrictions generated by Restriction Generator"
    )
    (build_dir / "pack.mcmeta").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    warnings: list[str] = []
    count = 0
    seen: set[str] = set()
    for row in rows:
        if not row.enabled:
            continue
        item_id = row.item_id.strip().lower()
        if not re.fullmatch(r"[a-z0-9_.-]+:[a-z0-9_./-]+", item_id):
            warnings.append(
                f"Skipped invalid ID: {row.item_id}"
                if language == "en"
                else f"Pominięto nieprawidłowe ID: {row.item_id}"
            )
            continue
        key = (
            f"{item_id}|{row.use_job}|{row.use_level}|"
            f"{row.smith_job}|{row.smith_level}|{row.enchant_job}|"
            f"{row.enchant_level}|{row.repair_job}|"
            f"{row.repair_level}|{row.use_types}"
        )
        if key in seen:
            warnings.append(
                f"Skipped duplicate: {item_id}"
                if language == "en"
                else f"Pominięto duplikat: {item_id}"
            )
            continue
        seen.add(key)
        if row.smith_job != "none" and row.smith_level > 0:
            data = restriction_json(
                item_id,
                row.smith_job,
                row.smith_level,
                ["craft"],
            )
            path = restrictions_dir / (
                f"{safe_name(item_id)}__craft_"
                f"{row.smith_job}_{row.smith_level}.json"
            )
            path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
            count += 1
        requested_types = [x.strip() for x in row.use_types.split(",") if x.strip()]
        types = []
        for restriction_type in requested_types:
            if restriction_type not in SUPPORTED_RESTRICTION_TYPES:
                warnings.append(
                    (
                        f"Skipped unsupported type '{restriction_type}' for {item_id}"
                        if language == "en"
                        else f"Pominięto nieobsługiwany typ '{restriction_type}' dla {item_id}"
                    )
                )
                continue
            if restriction_type not in USE_RESTRICTION_TYPES:
                warnings.append(
                    (
                        f"Type '{restriction_type}' for {item_id} is not a use restriction"
                        if language == "en"
                        else f"Typ '{restriction_type}' dla {item_id} nie jest restrykcją używania"
                    )
                )
                continue
            if restriction_type not in types:
                types.append(restriction_type)
        if row.use_job in {"warrior", "hunter"} and "hurt_entity" in types:
            # Broń ma być bezużyteczna także do niszczenia bloków.
            if "item_break_block" not in types:
                types.append("item_break_block")
        if row.use_job != "none" and row.use_level > 0 and types:
            data = restriction_json(item_id, row.use_job, row.use_level, types)
            path = restrictions_dir / f"{safe_name(item_id)}__use_{row.use_job}_{row.use_level}.json"
            path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
            count += 1
        if row.enchant_job != "none" and row.enchant_level > 0:
            data = restriction_json(
                item_id,
                row.enchant_job,
                row.enchant_level,
                ["enchant"],
            )
            path = restrictions_dir / (
                f"{safe_name(item_id)}__enchant_"
                f"{row.enchant_job}_{row.enchant_level}.json"
            )
            path.write_text(
                json.dumps(data, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            count += 1
        if row.repair_job != "none" and row.repair_level > 0:
            data = restriction_json(
                item_id,
                row.repair_job,
                row.repair_level,
                ["repair"],
            )
            path = restrictions_dir / (
                f"{safe_name(item_id)}__repair_"
                f"{row.repair_job}_{row.repair_level}.json"
            )
            path.write_text(
                json.dumps(data, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            count += 1
    destination_zip.parent.mkdir(parents=True, exist_ok=True)
    if destination_zip.exists():
        destination_zip.unlink()
    with zipfile.ZipFile(destination_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in build_dir.rglob("*"):
            if file.is_file():
                zf.write(file, file.relative_to(build_dir).as_posix())
    shutil.rmtree(build_dir)
    return count, warnings
